Mydevnullnet\Bundle\PublierBundle\Entity\Post:
  type: entity
  repositoryClass: Mydevnullnet\Bundle\PublierBundle\Repository\PostRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:        { type: string   }
    body:         { type: string   }
    slug:         { type: string   }
    created_at:   { type: datetime }
    publish_date: { type: datetime }
    in_stream:    { type: boolean  }
    in_menu:      { type: boolean  }

