Mydevnullnet\Bundle\PublierBundle\Entity\User:
  type: entity
  repositoryClass: Mydevnullnet\Bundle\PublierBundle\Repository\UserRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username: { type: string }
    email:    { type: string }
    password: { type: string }
    salt:     { type: string }

