mydevnullnet_publier_home:
    pattern:  /
    defaults: { _controller: MydevnullnetPublierBundle:Site:index }

mydevnullnet_publier_404:
    pattern:  /404
    defaults: { _controller: MydevnullnetPublierBundle:Error:index }

mydevnullnet_publier_install:
    pattern:  /install
    defaults: { _controller: MydevnullnetPublierBundle:Site:install }
    
mydevnullnet_publier_posts:
    pattern:  /posts
    defaults: { _controller: MydevnullnetPublierBundle:Site:posts }

mydevnullnet_publier_login:
    pattern:  /log-in
    defaults: { _controller: MydevnullnetPublierBundle:User:login }

mydevnullnet_publier_logout:
    pattern:  /log-out
    defaults: { _controller: MydevnullnetPublierBundle:User:logout }

mydevnullnet_publier_settings:
    pattern:  /settings
    defaults: { _controller: MydevnullnetPublierBundle:User:settings }

mydevnullnet_publier_post_new:
    pattern:  /new
    defaults: { _controller: MydevnullnetPublierBundle:Post:new }

mydevnullnet_publier_post_edit:
    pattern:  /edit/{id}
    defaults: { _controller: MydevnullnetPublierBundle:Post:edit }

mydevnullnet_publier_post_publish:
    pattern:  /publish/{id}
    defaults: { _controller: MydevnullnetPublierBundle:Post:publish }

mydevnullnet_publier_post_archive:
    pattern:  /archive/{id}
    defaults: { _controller: MydevnullnetPublierBundle:Post:archive }

mydevnullnet_publier_post_load_without_slug:
    pattern:  /post/{id}
    defaults: { _controller: MydevnullnetPublierBundle:Post:load }

mydevnullnet_publier_post_load_with_slug:
    pattern:  /{slug}
    defaults: { _controller: MydevnullnetPublierBundle:Post:load }



