parameters:
#    mydevnullnet_publier.example.class: Mydevnullnet\Bundle\PublierBundle\Example

services:
#    mydevnullnet_publier.example:
#        class: %mydevnullnet_publier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
