parameters:
    database_driver:   pdo_sqlite
    database_host:     localhost
    database_port:     ~
    database_name:     publier
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            superyeahawesomesecrettoken

    sqlite_driver: pdo_sqlite
    sqlite_path: %kernel.root_dir%/sqlite_publier.db
