parameters:
    database_driver:   pdo_sqlite
    database_host:     localhost
    database_port:     ~
    database_name:     publier.db
    database_user:     root
    database_password: ~
    database_path:     %kernel.root_dir%/db/publier.db

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            superyeahawesomesecrettoken

